spring:
  application:
    name: shop-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pass
    url: jdbc:mysql://localhost:3306/furnituredb
    username: root
  jpa:
    open-in-view: true

security:
  jwt:
    token:
      secret-key: "jwtsecret"